name: Publish package to GitHub Packages
on:
  push:
  pull_request:

jobs:
  publish:
    runs-on: windows-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Publish package
        run: |
          cd code
          mvn --batch-mode validate deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
